#!/usr/bin/env python3
"""End-to-end harness for AI Agent Bridge (docs/design/phase1-2-spec.md
"Harness"). Builds the service if needed, starts a headless rig server with
the companion mod (and the test provider mod, if it exists yet) linked in,
starts the service against it with the deterministic fake model, runs every
scenario in scenarios.py, prints one PASS/FAIL/SKIP line each, tears
everything down, and exits non-zero if any scenario failed.

    python3 tests/e2e/run.py             # server + service only
    python3 tests/e2e/run.py --client     # also a standalone client, for the
                                          # scenarios that need a real player

Env vars (all optional):
    FACTORIO_HEADLESS   headless server binary (default: see rig.py)
    FACTORIO_CLIENT     standalone client binary, only used with --client
    SERVICE_BIN         path to a prebuilt `aab`; skips the Docker build

Python 3 standard library only.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import textwrap
import time
import urllib.error
import urllib.request
from pathlib import Path

import rig
import scenarios

REPO_ROOT = rig.REPO_ROOT
RUN_ROOT = rig.DEFAULT_RUN_ROOT
CONTROL_API_ADDR = "127.0.0.1:8090"


def build_service() -> Path:
    """Returns a path to the `aab` binary, building it through Docker (no Go
    toolchain assumed on the host) unless SERVICE_BIN names an existing one."""
    env_bin = os.environ.get("SERVICE_BIN")
    if env_bin:
        path = Path(env_bin)
        if not path.is_file():
            raise FileNotFoundError("SERVICE_BIN=%s does not exist" % env_bin)
        return path

    service_dir = REPO_ROOT / "service"
    out = service_dir / "aab"
    cmd = [
        "docker", "run", "--rm",
        "-v", "%s:/src" % service_dir,
        "-w", "/src",
        "-e", "CGO_ENABLED=0",
        "-v", "aab-gomod:/go/pkg/mod",
        "golang:1.25-alpine",
        "go", "build", "-o", "aab", "./cmd/aab",
    ]
    print("run.py: building service (docker build)...")
    subprocess.run(cmd, check=True, cwd=str(service_dir))
    if not out.is_file():
        raise RuntimeError("docker build reported success but %s is missing" % out)
    return out


def write_config(run_root: Path, server: "rig.Server") -> Path:
    """Writes tests/e2e/.run/aab.e2e.yaml: model "fake" (the scripted,
    deterministic model, docs/design/phase1-2-spec.md "Fake model"), RCON
    at the rig server, events file inside its own write-data, history and
    control API local to this run."""
    cfg_path = run_root / "aab.e2e.yaml"
    history_path = run_root / "history.sqlite"
    content = textwrap.dedent(
        """\
        # Generated by tests/e2e/run.py at %s. Do not edit by hand; edit
        # write_config() there and re-run instead.
        factorio:
          rcon:
            address: 127.0.0.1:%d
            password_env: FACTORIO_RCON_PASSWORD
          events_file: %s

        transport: local
        poll_interval: 300ms

        anthropic:
          api_key_env: ANTHROPIC_API_KEY
          model: fake

        agent:
          max_rounds: 6
          max_tokens_per_question: 20000
          memory_ttl: 10m
          questions_per_player_per_hour: 20

        history:
          path: %s

        control_api:
          addr: %s
        """
    ) % (time.strftime("%Y-%m-%dT%H:%M:%S"), server.rcon_port, server.events_file, history_path, CONTROL_API_ADDR)
    cfg_path.write_text(content, encoding="utf-8")
    return cfg_path


def start_service(service_bin: Path, cfg_path: Path, run_root: Path, rcon_password: str) -> subprocess.Popen:
    log_path = run_root / "service.log"
    env = dict(os.environ)
    env["FACTORIO_RCON_PASSWORD"] = rcon_password
    # ANTHROPIC_API_KEY is deliberately left whatever (or absent) it already
    # is: model "fake" never calls the Anthropic API, and there is no key on
    # this machine (see the task brief this harness was written against).
    log_file = open(log_path, "w", encoding="utf-8")
    proc = subprocess.Popen(
        [str(service_bin), "run", "-config", str(cfg_path)],
        cwd=str(run_root),
        stdout=log_file,
        stderr=subprocess.STDOUT,
        env=env,
    )
    proc._aab_log_file = log_file  # keep it alive; closed in stop_service
    return proc


def stop_service(proc):
    if proc is None:
        return
    if proc.poll() is None:
        proc.terminate()
        try:
            proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=15)
    log_file = getattr(proc, "_aab_log_file", None)
    if log_file is not None:
        log_file.close()


def wait_for_service_ready(addr: str, timeout: float, proc: subprocess.Popen, log_path: Path) -> None:
    url = "http://%s/healthz" % addr
    deadline = time.monotonic() + timeout
    last_err = None
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            text = log_path.read_text(encoding="utf-8", errors="replace") if log_path.exists() else ""
            raise RuntimeError(
                "service process exited (code %s) before %s answered:\n%s" % (proc.returncode, url, text[-2000:])
            )
        try:
            with urllib.request.urlopen(url, timeout=2) as resp:
                if resp.status == 200:
                    return
        except (urllib.error.URLError, OSError) as e:
            last_err = e
        time.sleep(1)
    raise TimeoutError("%s did not answer within %ss (last error: %r)" % (url, timeout, last_err))


def resolve_client_player_index(server_rcon: "rig.RCON", timeout: float = 20.0, interval: float = 0.5):
    """Waits for the standalone client to actually be in game.connected_players
    and returns its LuaPlayer index, rather than assuming which index a fresh
    join gets."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        reply = server_rcon.command(
            '/sc rcon.print(#game.connected_players > 0 and tostring(game.connected_players[1].index) or "none")'
        ).strip()
        if reply != "none":
            try:
                return int(reply)
            except ValueError:
                pass
        time.sleep(interval)
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--client", action="store_true", help="also launch a standalone client and run the player-only scenarios")
    parser.add_argument("--keep", action="store_true", help="leave the server/client/service running after the run for manual inspection")
    parser.add_argument("--answer-timeout", type=float, default=25.0, help="seconds to wait for a question to be answered (default 25)")
    args = parser.parse_args()

    RUN_ROOT.mkdir(parents=True, exist_ok=True)

    mods = [rig.companion_mod()]
    provider = rig.provider_mod()
    if provider is not None:
        mods.append(provider)
    mods_dir = rig.ensure_mods_dir(RUN_ROOT / "mods", mods)
    # The chat-prefix scenario needs a runtime-global setting that no console
    # command may write (see rig.CHAT_PREFIX), so it is seeded here, before the
    # map exists.
    headless_bin = Path(rig.default_headless_bin())
    rig.write_mod_settings(
        mods_dir,
        {"aab-chat-prefix": rig.CHAT_PREFIX},
        version=rig.binary_version(headless_bin),
    )
    print("run.py: mods dir %s: %s" % (mods_dir, ", ".join("%s %s" % (m.name, m.version) for m in mods)))
    if provider is None:
        print("run.py: tests/provider-mod not found yet; provider-dependent scenarios will SKIP")

    server = rig.Server(name="server", run_root=RUN_ROOT, mods_dir=mods_dir)
    client = rig.Client(server, name="client", run_root=RUN_ROOT, mods_dir=mods_dir) if args.client else None
    service_proc = None
    server_rcon = None
    exit_code = 1

    try:
        print("run.py: starting rig server on game=%d rcon=%d ..." % (server.game_port, server.rcon_port))
        server.start()
        print("run.py: server up, log at %s" % server.log_path)

        if client is not None:
            print("run.py: starting standalone client ...")
            client.start()
            print("run.py: client up, log at %s" % client.log_path)

        service_bin = build_service()
        cfg_path = write_config(RUN_ROOT, server)
        print("run.py: starting service (%s run -config %s) ..." % (service_bin, cfg_path))
        service_proc = start_service(service_bin, cfg_path, RUN_ROOT, server.rcon_password)
        wait_for_service_ready(CONTROL_API_ADDR, timeout=30, proc=service_proc, log_path=RUN_ROOT / "service.log")
        print("run.py: service up, control API at http://%s" % CONTROL_API_ADDR)

        server_rcon = server.rcon()

        client_player_index = None
        if client is not None:
            client_player_index = resolve_client_player_index(server_rcon)
            if client_player_index is None:
                print("run.py: WARNING: client never appeared in game.connected_players; player-only scenarios will fail")
            else:
                print("run.py: client is player_index=%d" % client_player_index)

        provider_iface = scenarios.find_provider_iface(server_rcon)
        ctx = scenarios.Ctx(
            server_rcon=server_rcon,
            client_player_index=client_player_index,
            provider_iface=provider_iface,
            answer_timeout=args.answer_timeout,
        )

        print("run.py: running scenarios ...")
        results = scenarios.run_all(ctx, with_client=args.client)
        print("")
        for r in results:
            print(r.line())
        print("")

        failed = [r for r in results if r.status == "FAIL"]
        passed = [r for r in results if r.status == "PASS"]
        skipped = [r for r in results if r.status == "SKIP"]
        print("run.py: %d passed, %d failed, %d skipped" % (len(passed), len(failed), len(skipped)))
        exit_code = 1 if failed else 0

    finally:
        if server_rcon is not None:
            server_rcon.close()
        if not args.keep:
            stop_service(service_proc)
            if client is not None:
                client.stop()
            server.stop()
        else:
            print("run.py: --keep set, leaving server/client/service running (rcon %d, control API %s)" % (server.rcon_port, CONTROL_API_ADDR))

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
